### ISSUE TITLE
c++ files compiled with the c profile

### ISSUE THREAD

**Issue by ismail** [kosh04/emacs-wandbox#15]
I have a C++ file with extension cpp and trying to run wandbox-compile-buffer fails because it uses the gcc-head-c profile. In the profiles list I don't see any specific C++ profile either. Could you please let me know the proper way to select the right C++ profile?

**Comment by kosh04** [comment]
Now cpp extension files will execute with gcc-head compiler (as C++).

Thanks issue, wait for untill MELPA update.

**Comment by ismail** [comment]
This now works as expected, thanks!
