### ISSUE TITLE
Cannot select language standard?

### ISSUE THREAD

**Issue by FirstLoveLife** [kosh04/emacs-wandbox#17]
init.el:
```
 (:name "C++" :compiler "clang-head" :options "warning,boost-1.55,sprout,gnu++1y" :ext "cc")))))
```

```
## clang-head
* [compiler_message]
prog.cc:5:10: error: no member named 'optional' in namespace 'std'
    std::optional<int> a;
    ~~~~~^
prog.cc:5:22: error: expected '(' for function-style cast or type construction
    std::optional<int> a;
                  ~~~^
prog.cc:5:24: error: use of undeclared identifier 'a'
    std::optional<int> a;
                       ^
3 errors generated.

* [status]
1
```
I have turned on `gun++1y` in `:options`, but wandbox.el seems cannot regonize this option. How can I fix? thx.

**Comment by kosh04** [comment]
> init.el:
> 
>  (:name "C++" :compiler "clang-head" :options "warning,boost-1.55,sprout,gnu++1y" :ext "cc")))))

your init.el code looks like invalid things. 🤔 

In addition, `std::optional<T>` requires C++17 or later. however `gnu++1y` option provides C++14.
you shoud use `gnu++17` (or `gnu++1z`) option.

Example:
```emacs-lisp
(wandbox :file "/path/to/example.cc"  :compiler "clang-head" :options "warning,gnu++1z")
```

please more detail, your init.el about wandbox & your C++ full snippet.

**Comment by FirstLoveLife** [comment]
@kosh04 My bad. Thanks for your review, now it works fine.
