### ISSUE TITLE
Failed to compile code.

### ISSUE THREAD

**Issue by beacoder** [kosh04/emacs-wandbox#20]
Hi,
I install this package from melpa.
then I executed this: (require 'wandbox)
and created a new buffer with following content:

```
#include <iostream>

int main()
{
    std::cout<<"Hello World";

    return 0;
}
```

then I execute wandbox, and got result:
```
## gcc-11.1.0-c
* [compiler_message]
prog.c:1:10: fatal error: iostream: No such file or directory
    1 | #include <iostream>
      |          ^~~~~~~~~~
compilation terminated.

* [program_message]

* [status]
1
```

Could u please help to have a check, is it because I forget to config something which led to this error ?
Cuz from my understanding, all the related std files should be in the server side, so seems this error don't make any sense.

many thanks.

**Comment by kosh04** [comment]
What file name did you execute?
The compiler used by emacs-wandbox at runtime is based on the file extension.

In your issue, you are trying to run a `gcc-11.1.0-c`, i.e. a C++ program with a C compiler (not C++).
In emacs-wandbox, `.c` extensions such as `program.c` try to run as C programs.

If you want to run a C++ program, specify the filename extension as `.cc` `.cpp`, etc.

Tips: If you use code block syntax, you can paste error messages correctly.
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by beacoder** [comment]
oh, I see, so I tried to save these into a file and then execute, it got passed.
so it seems like I have to save the code snippet into a file first.
previously I was trying to like changing the buffer mode to c++-mode, or like changing the buffer name to something with .cpp as postfix, seems all not working..

can only work, when I save the code into some file with .cpp extention.

@kosh04 , anyway, thanks for the prompt response, appreciated.

can I offer one advice, take me for example, the most common scenario for me to use this wandbox is that when I encounter some thing I'm not certain about, then I might want to use this wandbox to verify it.
but as you see, it's kind of like a random stuff, so I probabitly wont't want to save it to any files.
so is there any chance that you could provide something like compile the selection-region codes based on 
buffer mode instead of just by file extention ?
or even better you could figure out the language choice based on the selected code.

**Comment by beacoder** [comment]
again, thanks for providing this useful utility.

**Comment by kosh04** [comment]
You can also specify the language in the buffer header as follows. (It's experimental features)

```
// #wandbox lang: c++
or
// #wandbox compiler: clang-head
#include <iostream>
int main() {...}
```

The automatic language selection from a code fragment is attractive but not plan to provide.
Since the Wandbox web service can run numerous languages, it is not practical to support them all.

p.s. Thanks for using this tool 😃

**Comment by beacoder** [comment]
oh, thanks for the tips, keep up the great work.
I will close this issue now.
