### ISSUE TITLE
error: Package ‘tabulated-list-1.0’ is unavailable

### ISSUE THREAD

**Issue by ismail** [kosh04/emacs-wandbox#7]
While trying to install emacs-wandbox via melpa I get:

error: Package ‘tabulated-list-1.0’ is unavailable

This is on emacs 24.5 where tabulated-list-mode seems to be available by default.

**Comment by kosh04** [comment]
Thanks for report. It fixed.

Probably, I think it was cause that [emacs-lisp/package.el](https://github.com/emacs-mirror/emacs/blob/emacs-24/lisp/emacs-lisp/package.el) file header in reference.
`;; Package-Requires: ((tabulated-list "1.0"))`

**Comment by ismail** [comment]
Can you also update the melpa package? Thanks a lot!

**Comment by kosh04** [comment]
Melpa's package update will be done automatically in hours. Please wait.

**Comment by ismail** [comment]
Works now, thanks!
